require "time"
require "aws-sdk"

require "newrelic_aws/collectors/base"
require "newrelic_aws/collectors/ec2"
require "newrelic_aws/collectors/ebs"
require "newrelic_aws/collectors/elb"
require "newrelic_aws/collectors/rds"
require "newrelic_aws/collectors/ddb"
require "newrelic_aws/collectors/sqs"
require "newrelic_aws/collectors/sns"
require "newrelic_aws/collectors/ec"
require "newrelic_aws/collectors/ecr"
